"""Domain business entities representing Dhaba tickets, billing facts, and decisions."""

from datetime import datetime
from typing import Tuple
from pydantic import BaseModel, ConfigDict, Field

from app.domain.enums import Category, PurchaseStatus, PurchaseType, Severity


class Purchase(BaseModel):
    """Authoritative billing transaction record known at ticket arrival time."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    id: str = Field(min_length=1, description="Unique billing transaction identifier (e.g. pay_A1)")
    type: PurchaseType = Field(description="Transaction type: trial or renewal")
    amount_inr: int = Field(ge=0, description="Exact integer transaction amount in INR (no floats)")
    status: PurchaseStatus = Field(description="Settlement status: initiated, failed, or successful")
    at: datetime = Field(description="ISO8601 timestamp when transaction occurred")


class Ticket(BaseModel):
    """Core domain representation of a customer support ticket and its billing snapshot."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    id: str = Field(min_length=1, description="Unique ticket identifier (e.g. T-1001)")
    received_at: datetime = Field(description="Timestamp when ticket was received")
    subject: str = Field(min_length=1, description="Customer-provided subject line")
    body: str = Field(min_length=1, description="Raw customer message body (untrusted text)")
    purchases: Tuple[Purchase, ...] = Field(
        default_factory=tuple,
        description="Chronological billing transactions associated with this user",
    )
    app_opens_since_renewal: int = Field(
        ge=0,
        description="Number of times user launched the app after their most recent renewal",
    )


class RefundDecision(BaseModel):
    """Deterministic financial determination generated by the business policy gate.

    Note: This is an analytical decision/recommendation for the support tool.
    It does not claim to have executed a bank transfer.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    should_refund: bool = Field(description="Whether a refund is authorized by policy")
    amount_inr: int = Field(ge=0, description="Authorized refund amount in INR (0 if not authorized)")
    reason: str = Field(min_length=1, description="Documented deterministic justification for decision")
    eligible_purchase_ids: Tuple[str, ...] = Field(
        default_factory=tuple,
        description="Transaction IDs authorized for refund, if any",
    )


class TriageResult(BaseModel):
    """Complete domain triage outcome combining perception and business policy."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    ticket_id: str = Field(min_length=1, description="Target ticket ID")
    category: Category = Field(description="Assigned ticket category")
    severity: Severity = Field(description="Assigned severity level")
    refund: RefundDecision = Field(description="Deterministic refund decision")
    reply_draft: str = Field(min_length=1, description="Customer-facing reply draft in customer language")
    needs_human: bool = Field(description="True if human intervention or review is required")
    confidence: float = Field(ge=0.0, le=1.0, description="Classification confidence score [0.0, 1.0]")
    degraded: bool = Field(default=False, description="True if produced by fallback degradation")
    triaged_at: datetime = Field(description="Timestamp when triage was completed")
